### ISSUE TITLE
Implement 2.01 "9. Organisation and Activity Identifiers"

### ISSUE THREAD

**Issue by Bjwebb** [IATI/IATI-Schemas#231]
http://support.iatistandard.org/entries/52824355-Version-2-01-Iteration-3-9-Organisation-and-Activity-Identifiers

This has multiple sections:
- [x] Reporting organisation
- [x] IATI activity identifier
- [x] Other-identifier https://github.com/IATI/IATI-Schemas/issues/228
- [ ] IATI Organisation Codelist

**Comment by Bjwebb** [comment]
Parts of the support forum page have already been covered by other issues. These are the remaining tasks that I think are not listed elsewhere on GitHub:

## Reporting organisation

> It is recommended that non-publishing organisations referred to in participating-org/@ref, transaction/provider-org/@ref and transaction/receiver-org/@ref are assigned valid organisation identifiers, but this is NOT mandatory

~~Schema definitions need to be changed to ensure this is no longer mandatory.:~~

~~\- [ ] http://dev.iatistandard.org/201/activity-standard/iati-activities/iati-activity/participating-org/#attributes~~
~~\- [ ] http://dev.iatistandard.org/201/activity-standard/iati-activities/iati-activity/transaction/provider-org/#attributes~~
~~\- [ ] http://dev.iatistandard.org/201/activity-standard/iati-activities/iati-activity/transaction/receiver-org/#attributes~~

~~(see https://github.com/IATI/IATI-Schemas/issues/237 for more details about the description change)~~

[edit: I misunderstood the intent of the proposal here. https://github.com/IATI/IATI-Schemas/issues/237#issuecomment-56803268 ]
- [x] Clarify the proposal on the knowledge-base
- [x] Add necessary rules to https://github.com/IATI/IATI-Extra-Documentation/issues/250

## IATI activity identifier

http://dev.iatistandard.org/201/activity-standard/iati-activities/iati-activity/iati-identifier/

> Once an activity has been reported to IATI its identifier MUST NOT be changed in subsequent updates, 
- [x] This needs adding to the schema description https://github.com/IATI/IATI-Schemas/issues/237
- [x] This needs adding to the manual rules https://github.com/IATI/IATI-Extra-Documentation/issues/250

> It MUST be prefixed with EITHER the organisation-identifier found in reporting-org/@ref OR a previous reporting-org identifier reported in other-identifier
- [x] This needs changing in the schema description https://github.com/IATI/IATI-Schemas/issues/237
- [x] This needs changing in the manual rules https://github.com/IATI/IATI-Extra-Documentation/issues/250

## IATI Organisation Codelist

> IATI will establish its own registration agency with a published list of registered identifiers
> 
> The prefix for this agency will be ??-IATI . (NB it has been pointed out that the "XM" prefix has been 'defined' as "multilateral" and is therefore not appropriate for IATI. [XI - for international organisations?] )

@bill-anderson Are you able to make a decision on exactly what the prefix will be?
- [x] The prefix then needs to be added to the OrganisationRegistrationAgency codelist
  See: https://github.com/IATI/IATI-Codelists-NonEmbedded/issues/22

> This list will initially be populated with ALL currently valid identifiers that are in use and that do not have a valid prefix.
- [x] Create this list https://github.com/IATI/IATI-Codelists-NonEmbedded/issues/32

> While many of these identifiers have been derived from DAC codes, this 'meaning' is not carried forward. i.e. IATI generated identifiers have no intrinsic meaning.
- [ ] This should be added to the description of the codelist https://github.com/IATI/IATI-Codelists-NonEmbedded/issues/33

> Any publisher may request IATI to generate a code for it. This will be a manual process with a quick turnaround.
- [ ] The process for this should be decided, and added as guidance. https://github.com/IATI/IATI-Guidance/issues/166

**Comment by bill-anderson** [comment]
XI-IATI for IATI Reg Agency

**Comment by Bjwebb** [comment]
@caprenter Could you look into the "IATI Organisation Codelist" tasks here?

**Comment by Bjwebb** [comment]
Closing this, as the remaining tasks are covered by other issue.
