### ISSUE TITLE
Add new @budget-not-provided attribute for the iati-activity element

### ISSUE THREAD

**Issue by dalepotter** [IATI/IATI-Schemas#337]
Add a new attribute at `iati-activities/iati-activity/@budget-not-provided`, with the following definition:

> A code indicating the reason why this activity does not contain any iati-activity/budget elements. The value must exist in the BudgetNotProvided codelist.

The attribute will have type `xsd:string` with occurrence rule `0..1`.

**Tasks:**

- [x] Add tests
- [x] Add `iati-activities/iati-activity/@budget-not-provided`
- [x] Update Codelist mapping file: `IATI-Codelists/mapping.xml` (to link this attribute to the `BudgetNotProvided` codelist)
- [x] Add `BudgetNotProvided` codelist to the IATI-Codelist-NonEmbedded repository https://github.com/IATI/IATI-Codelists-NonEmbedded/issues/183.

**Comment by andylolz** [comment]
The title and description of this issue don’t seem to be related. Should this be two issues?

**Comment by dalepotter** [comment]
@andylolz good spot - somehow these two issues got mixed up. The new attribute `iati-activities/iati-activity/default-aid-type/@vocabulary` has now been added as #346.

**Comment by andylolz** [comment]
Reiterating [my comment here](https://discuss.iatistandard.org/t/final-technical-proposal-for-the-2-03-upgrade/1097/15), that `budget-omitted` might be a pithier name than `budget-not-provided`, and is marginally easier to parse in instances where `budget-not-provided="false"`.

**Comment by hayfield** [comment]
**EDIT:** As noted by @andylolz, it's proposed that there is a Codelist rather than boolean value. As such, the below isn't a correct argument. The name is, however, [`rather cumbersome`](https://discuss.iatistandard.org/t/add-budget-exempt-attribute-and-codelist-included-2-03/845/10?u=hayfield).

---

Agree with @andylolz's suggestion for a different name.

---

The current proposal of `budget-not-provided` includes a negation in the name.

* When the value is `false`, this leads to a somewhat unnecessary double-negative. Double-negatives are inherently complex to interpret.
* When the value is `true` there is an unnecessary negative that complicates parsing of the meaning.

The one slight issue is that `omitted` is not quite as common a word as `provided`. Assuming there is a clear definition, I feel this is a smaller issue than the unnecessary negative.

**Comment by andylolz** [comment]
Apologies – I’ve just realised/remembered that [the proposed attribute](https://discuss.iatistandard.org/t/add-budget-exempt-attribute-and-codelist-included-2-03/845) isn’t a boolean, but rather a string that references a codelist. So I was mistaken about the double negative issue, and I’m not sure there’s much of a case for using ‘omitted’ over ‘not provided’.

**Comment by andylolz** [comment]
Since [the related discuss topic](https://discuss.iatistandard.org/t/add-budget-exempt-attribute-and-codelist-included-2-03/845) is closed, I’ll add a comment here.

The [notes from the consultation call](https://discuss.iatistandard.org/t/add-budget-exempt-attribute-and-codelist-included-2-03/845/9) say:

> there was no objection from the group about the inclusion of the attribute `@budget-exempt`

While we didn’t raise objections on the call, we did raise concerns that the proposal is incomplete as it stands. As per [the comment made here](https://discuss.iatistandard.org/t/add-budget-exempt-attribute-and-codelist-included-2-03/845/7) on behalf of Publish What You Fund, we’d like to see “justification as to how publishing the redacted information would cause material or direct harm.”

Further, from a technical perspective, [this comment](https://discuss.iatistandard.org/t/add-budget-exempt-attribute-and-codelist-included-2-03/845/3) from @markbrough makes a case for not adding an attribute specifically about the `budget` element, but instead generalising to other elements. Based on the elements publishers tell us they aren’t able to publish, we could imagine the following down the road:

```xml
<iati activity budget-not-provided="1" subnational-location-not-provided="1" contracts-not-provided="1" disbursements-not-provided="1" implementer-not-provided="1">
    […]
</iati-activity>
```

So, here’s a more generalised (pseudocode) implementation:

```xml
<not-provided name="budget" reason="1">
  <justification>
    <narrative>
      Providing budgets would cause material or direct harm because &hellip;
    </narrative>
  </justification>
</not-provided>
```

**Comment by allthatilk** [comment]
@hayfield @dalepotter  Can I get a follow up on what's happening with this one please?

**Comment by hayfield** [comment]
Requires input from @IATI/bas

**Comment by PetyaKangalova** [comment]
@andylolz  Apologies for the delayed response. As part of the consultation, @bill-anderson  addressed Mark's concerns that you have referred to above and why the proposal is not normalised to all elements but only [concerning forward-looking and adding the budget attribute](https://discuss.iatistandard.org/t/add-budget-exempt-attribute-and-codelist-included-2-03/845/10 ).
As part of the 2.03 upgrade the specific proposal was to include the attribute  `@budget-not-provided`  and that is what we are currently proceeding with.

In the final technical proposal post on [Discuss](https://discuss.iatistandard.org/t/final-technical-proposal-for-the-2-03-upgrade/1097?u=iati-techteam) there has been no opposition to this proposal. You have [suggested an alternative name](https://discuss.iatistandard.org/t/final-technical-proposal-for-the-2-03-upgrade/1097/15) @budget-omitted. We have not heard back from the community on whether they support the suggested alternative, so let us know if you feel strongly that the name should be changed.

**Comment by andylolz** [comment]
> You have suggested an alternative name @budget-omitted […] let us know if you feel strongly that the name should be changed.

[In my post above](https://github.com/IATI/IATI-Schemas/issues/337#issuecomment-345996471) I acknowledged this was my mistake. So I withdraw this suggestion.

**Comment by andylolz** [comment]
> In the final technical proposal post on Discuss there has been no opposition to this proposal.

It’s true that we didn’t raise this issue on the final technical proposal post on Discuss. We did raise it [on the proposal’s discuss post](https://discuss.iatistandard.org/t/add-budget-exempt-attribute-and-codelist-included-2-03/845/7), on the consultation call, [and above](https://github.com/IATI/IATI-Schemas/issues/337#issuecomment-346071681).

**Comment by bill-anderson** [comment]
@andylolz I believe we have consulted fully on these issues.

- Extending the flag to cover other elements
Forward-looking data is a cornerstone of IATI's USP and is therefore a special case

- "'commercial sensitivity’ might become the standard excuse for not providing information. IATI should be careful to avoid legitimising this."
In most instances non-disclosure of commercially sensitive data is enshrined in law or government policy. It is not the role of the standard to question this.
