### ISSUE TITLE
Update definition: [reporting/participating/reciever/provider]-org @ref attribute

### ISSUE THREAD

**Issue by allthatilk** [IATI/IATI-Schemas#339]
Update reporting-org ref attribute to read:

>Machine-readable identification string for the organisation issuing the report. Must be in the format {RegistrationAgency}-{RegistrationNumber} where {RegistrationAgency} is a valid code in the Organisation Registration Agency code list and {RegistrationNumber} is a valid identifier issued by the {RegistrationAgency}. If this is not present then the narrative MUST contain the name of the organisation.

**Values to update**

- [x] `iati-activities/iati-activity/participating-org/@ref` (located in [activity](https://github.com/IATI/IATI-Schemas/blob/version-2.02/iati-activities-schema.xsd#L267-L273)) - Fixed in IATI-Schemas/#400
- [x] `iati-activities/iati-activity/planned-disbursement/provider-org/@ref` (located in [activity](https://github.com/IATI/IATI-Schemas/blob/version-2.02/iati-activities-schema.xsd#L2359-L2366)) - Fixed in IATI-Schemas/#400
- [x] `iati-activities/iati-activity/planned-disbursement/receiver-org/@ref` (located in [activity](https://github.com/IATI/IATI-Schemas/blob/version-2.02/iati-activities-schema.xsd#L2411-L2418)) - Fixed in IATI-Schemas/#400
- [x] `iati-activities/iati-activity/transaction/provider-org/@ref` (located in [activity](https://github.com/IATI/IATI-Schemas/blob/version-2.02/iati-activities-schema.xsd#L1083-L1090)) - Fixed in IATI-Schemas/#400
- [x] `iati-activities/iati-activity/transaction/receiver-org/@ref`  (located in [activity](https://github.com/IATI/IATI-Schemas/blob/version-2.02/iati-activities-schema.xsd#L1118-L1121))
- [x] `iati-organisations/iati-organisation/organisation-identifier` (located in [org](https://github.com/IATI/IATI-Schemas/blob/version-2.02/iati-organisations-schema.xsd#L73-L78))
- [x] `iati-organisations/iati-organisation/recipient-org-budget/recipient-org/@ref` (located in [org](https://github.com/IATI/IATI-Schemas/blob/version-2.02/iati-organisations-schema.xsd#L283-L289))

**Comment by hayfield** [comment]
Need to see how the changes from https://discuss.iatistandard.org/t/final-technical-proposal-for-the-2-03-upgrade/1097/8 impact this issue.

**Comment by allthatilk** [comment]
@hayfield need to add recipient-org-budget @ref to checklist too

**Comment by PetyaKangalova** [comment]
1. Update the @ref to read as follows for all `[participating/receiver/provider]-org` @ref attribute: 

> Machine-readable identification string for the organisation issuing the report. Must be in the format {RegistrationAgency}-{RegistrationNumber} where {RegistrationAgency} is a valid code in the Organisation Registration Agency code list and {RegistrationNumber} is a valid identifier issued by the {RegistrationAgency}.  **If this is not present then the narrative MUST contain the name of the organisation.**

The last sentence of the description was initially omitted by mistake so it is not a new addition.

2. Note: @ref attribute for `reporting-org `should **not** be changed as @ref for `reporting-org` is mandatory. The description should read as follows:

> Machine-readable identification string for the organisation issuing the report. Must be in the format {RegistrationAgency}-{RegistrationNumber} where {RegistrationAgency} is a valid code in the Organisation Registration Agency code list and {RegistrationNumber} is a valid identifier issued by the {RegistrationAgency}.  

3. The rule for @ref should also be made consistent as per the spreadsheet.

**Comment by allthatilk** [comment]
@hayfield @dalepotter can I get a follow up on this one? I've updated the issue to reflect points 1 and 2 from @PetyaKangalova but I'm not sure what point 3 is about?

**Comment by hayfield** [comment]
@allthatilk Check the `Rule` column in the spreadsheet (it'll be noted in there).

**Comment by hayfield** [comment]
The spreadsheet notes that a new Guideline is to be added.

Ideally Guidelines would be represented as Optional Rulesets. Unfortunately, this isn't really the case at present. As such, the correct location for this information should be determined.

@IATI/bas - advice on the current / soon-to-be location that this info should be would be helpful!

**Comment by hayfield** [comment]
The spreadsheet notes that a new Guideline is to be added.

Ideally Guidelines would be represented as Optional Rulesets. Unfortunately, this isn't really the case at present. As such, the correct location for this information should be determined.

@IATI/bas - advice on the current / soon-to-be location that this info should be would be helpful!

**Comment by allthatilk** [comment]
@IATI/bas Need clarity on the `iati-organisations` changes too please =)

**Comment by hayfield** [comment]
Pending @IATI/bas response

**Comment by PetyaKangalova** [comment]
@allthatilk  The same applies for the organisation file:

`iati-organisations/iati-organisation/organisation-identifier` (located in org)- definition should **not** change- see below:

> Machine-readable identification string for the organisation issuing the report. Must be in the format {RegistrationAgency}-{RegistrationNumber} where {RegistrationAgency} is a valid code in the Organisation Registration Agency code list and {RegistrationNumber} is a valid identifier issued by the {RegistrationAgency}.


`iati-organisations/iati-organisation/recipient-org-budget/recipient-org/@ref` (located in org)- definition should change- see text below:

> Machine-readable identification string for the organisation issuing the report. Must be in the format {RegistrationAgency}-{RegistrationNumber} where {RegistrationAgency} is a valid code in the Organisation Registration Agency code list and {RegistrationNumber} is a valid identifier issued by the {RegistrationAgency}. If this is not present then the narrative MUST contain the name of the organisation.

**Comment by hayfield** [comment]
To try and summarise this thread...

---

>Machine-readable identification string for the organisation issuing the report. Must be in the format {RegistrationAgency}-{RegistrationNumber} where {RegistrationAgency} is a valid code in the Organisation Registration Agency code list and {RegistrationNumber} is a valid identifier issued by the {RegistrationAgency}. If this is not present then the narrative MUST contain the name of the organisation.

**Values to set to this**

- [x] `iati-activities/iati-activity/participating-org/@ref` (located in [activity](https://github.com/IATI/IATI-Schemas/blob/version-2.02/iati-activities-schema.xsd#L267-L273))
- [x] `iati-activities/iati-activity/planned-disbursement/provider-org/@ref` (located in [activity](https://github.com/IATI/IATI-Schemas/blob/version-2.02/iati-activities-schema.xsd#L2359-L2366))
- [x] `iati-activities/iati-activity/planned-disbursement/receiver-org/@ref` (located in [activity](https://github.com/IATI/IATI-Schemas/blob/version-2.02/iati-activities-schema.xsd#L2411-L2418))
- [x] `iati-activities/iati-activity/transaction/provider-org/@ref` (located in [activity](https://github.com/IATI/IATI-Schemas/blob/version-2.02/iati-activities-schema.xsd#L1083-L1090)) 
- [x] `iati-activities/iati-activity/transaction/receiver-org/@ref`  (located in [activity](https://github.com/IATI/IATI-Schemas/blob/version-2.02/iati-activities-schema.xsd#L1118-L1121))
- [x] `iati-organisations/iati-organisation/recipient-org-budget/recipient-org/@ref` (located in [org](https://github.com/IATI/IATI-Schemas/blob/version-2.02/iati-organisations-schema.xsd#L283-L289))

---

> Machine-readable identification string for the organisation issuing the report. Must be in the format {RegistrationAgency}-{RegistrationNumber} where {RegistrationAgency} is a valid code in the Organisation Registration Agency code list and {RegistrationNumber} is a valid identifier issued by the {RegistrationAgency}.

**Values to set to this**

- [x] `iati-activities/iati-activity/reporting-org/@ref`
- [x] `iati-organisations/iati-organisation/organisation-identifier`
