### ISSUE TITLE
Update occurrence: result indicator @value attributes

### ISSUE THREAD

**Issue by allthatilk** [IATI/IATI-Schemas#353]
Update the number of times the result indicator @value attribute can occur to:

>0..1

**Values to update**

- [x] `iati-activities/iati-activity/result/indicator/baseline/@value` (defined in [activity](https://github.com/IATI/IATI-Schemas/blob/89a23b7a14310fbc338b99ed4707944825729a80/iati-activities-schema.xsd#L1920)) - Done in IATI/IATI-Schemas#392
- [x] `iati-activities/iati-activity/result/indicator/period/target/@value` (defined in [activity](https://github.com/IATI/IATI-Schemas/blob/89a23b7a14310fbc338b99ed4707944825729a80/iati-activities-schema.xsd#L2029)) - Done in IATI/IATI-Schemas#392
- [x] `iati-activities/iati-activity/result/indicator/period/actual/@value` (defined in [activity](https://github.com/IATI/IATI-Schemas/blob/89a23b7a14310fbc338b99ed4707944825729a80/iati-activities-schema.xsd#L2099)) - Done in IATI/IATI-Schemas#392
- [x] Add Rules / Guidelines to cover:
  - [x]  The @value must be omitted for qualitative measures https://github.com/IATI/IATI-Rulesets/issues/52
  - [x]  The @value must be included for non-qualitative measures https://github.com/IATI/IATI-Rulesets/issues/51
  - [x]  The @value should be a valid number for all non-qualitative measures https://github.com/IATI/IATI-Schemas/pull/405

**Comment by hayfield** [comment]
Need to see how the changes from https://discuss.iatistandard.org/t/final-technical-proposal-for-the-2-03-upgrade/1097/9 impact this issue.

**Comment by amy-silcock** [comment]
Changed rule 3 from a must to a should:
"The @value should be a valid number for all non-qualitative measures"

**Comment by hayfield** [comment]
The Guideline should be added to the Schema.

Rules are noted at IATI/IATI-Rulesets#51 and IATI/IATI-Rulesets#52

**Comment by hayfield** [comment]
There is now a PR to add the Guideline to the Schema https://github.com/IATI/IATI-Schemas/pull/405
