### ISSUE TITLE
Add new document-link element (as a child of various result elements)

### ISSUE THREAD

**Issue by dalepotter** [IATI/IATI-Schemas#359]
Add a new `document-link` element at the following locations:
- `iati-activities/iati-activity/result/document-link`
- `iati-activities/iati-activity/result/indicator/document-link`
- `iati-activities/iati-activity/result/indicator/baseline/document-link`
- `iati-activities/iati-activity/result/indicator/period/target/document-link`
- `iati-activities/iati-activity/result/indicator/period/actual/document-link`

The element will have an occurrence rule of `0..*` at all of the above locations, and will have following definition:

> A link to an online, publicly accessible web page or document expanding on the result.

This change replicates the existing `iati-activities/iati-activity/document-link` element, with the addition of the new description element to be added in #357. 

**Tasks:**

- [x] Check for other instances of the `document-link` element (across the [activity](https://github.com/IATI/IATI-Schemas/blob/version-2.02/iati-activities-schema.xsd#L2749-L2834)) and [organisation](https://github.com/IATI/IATI-Schemas/blob/version-2.02/iati-organisations-schema.xsd#L758-L865) schemas. Create a new common element. - Done in IATI/IATI-Schemas#389
- [x] Add tests for all elements above - Done in IATI/IATI-Schemas#389
- [x] Add `iati-activities/iati-activity/result/document-link` - Done in IATI/IATI-Schemas#389
- [x] Add `iati-activities/iati-activity/result/indicator/document-link` - Done in IATI/IATI-Schemas#389
- [x] Add `iati-activities/iati-activity/result/indicator/baseline/document-link` - Done in IATI/IATI-Schemas#389
- [x] Add `iati-activities/iati-activity/result/indicator/period/target/document-link` - Done in IATI/IATI-Schemas#389
- [x] Add `iati-activities/iati-activity/result/indicator/period/actual/document-link` - Done in IATI/IATI-Schemas#389

- [x] Update Codelist mapping file for `iati-activities/iati-activity/result/document-link/@format` (to reference this attribute to the `FileFormat` codelist) - Done in IATI/IATI-Codelists#123
- [x] Update Codelist mapping file for `iati-activities/iati-activity/result/document-link/title/narrative/@xml:lang` (to reference this attribute to the `Language` codelist) - Not needed, as [paths for all `xml:lang` attributes already exist](https://github.com/IATI/IATI-Codelists/blob/694518226f67a5de88df251e27477d49cf29b4de/mapping.xml#L296-L299)
- [x] Update Codelist mapping file for `iati-activities/iati-activity/result/document-link/description/narrative/@xml:lang` (to reference this attribute to the `Language` codelist) - Not needed, as [paths for all `xml:lang` attributes already exist](https://github.com/IATI/IATI-Codelists/blob/694518226f67a5de88df251e27477d49cf29b4de/mapping.xml#L296-L299)
- [x] Update Codelist mapping file for `iati-activities/iati-activity/result/document-link/category/@code` (to reference this attribute to the `DocumentCategory` codelist) - Done in IATI/IATI-Codelists#123
- [x] Update Codelist mapping file for `iati-activities/iati-activity/result/document-link/language/@code` (to reference this attribute to the `Language` codelist) - Done in IATI/IATI-Codelists#123

- [x] Update Codelist mapping file for `iati-activities/iati-activity/result/indicator/document-link/@format` (to reference this attribute to the `FileFormat` codelist) - Done in IATI/IATI-Codelists#123
- [x] Update Codelist mapping file for `iati-activities/iati-activity/result/indicator/document-link/title/narrative/@xml:lang` (to reference this attribute to the `Language` codelist) - Not needed, as [paths for all `xml:lang` attributes already exist](https://github.com/IATI/IATI-Codelists/blob/694518226f67a5de88df251e27477d49cf29b4de/mapping.xml#L296-L299)
- [x] Update Codelist mapping file for `iati-activities/iati-activity/result/indicator/document-link/description/narrative/@xml:lang` (to reference this attribute to the `Language` codelist) - Not needed, as [paths for all `xml:lang` attributes already exist](https://github.com/IATI/IATI-Codelists/blob/694518226f67a5de88df251e27477d49cf29b4de/mapping.xml#L296-L299)
- [x] Update Codelist mapping file for `iati-activities/iati-activity/result/indicator/document-link/category/@code` (to reference this attribute to the `DocumentCategory` codelist) - Done in IATI/IATI-Codelists#123
- [x] Update Codelist mapping file for `iati-activities/iati-activity/result/indicator/document-link/language/@code` (to reference this attribute to the `Language` codelist) - Done in IATI/IATI-Codelists#123

- [x] Update Codelist mapping file for `iati-activities/iati-activity/result/indicator/baseline/document-link/@format` (to reference this attribute to the `FileFormat` codelist) - Done in IATI/IATI-Codelists#123
- [x] Update Codelist mapping file for `iati-activities/iati-activity/result/indicator/baseline/document-link/title/narrative/@xml:lang` (to reference this attribute to the `Language` codelist) - Not needed, as [paths for all `xml:lang` attributes already exist](https://github.com/IATI/IATI-Codelists/blob/694518226f67a5de88df251e27477d49cf29b4de/mapping.xml#L296-L299)
- [x] Update Codelist mapping file for `iati-activities/iati-activity/result/indicator/baseline/document-link/description/narrative/@xml:lang` (to reference this attribute to the `Language` codelist) - Not needed, as [paths for all `xml:lang` attributes already exist](https://github.com/IATI/IATI-Codelists/blob/694518226f67a5de88df251e27477d49cf29b4de/mapping.xml#L296-L299)
- [x] Update Codelist mapping file for `iati-activities/iati-activity/result/indicator/baseline/document-link/category/@code` (to reference this attribute to the `DocumentCategory` codelist) - Done in IATI/IATI-Codelists#123
- [x] Update Codelist mapping file for `iati-activities/iati-activity/result/indicator/baseline/document-link/language/@code` (to reference this attribute to the `Language` codelist) - Done in IATI/IATI-Codelists#123

- [x] Update Codelist mapping file for `iati-activities/iati-activity/result/indicator/period/target/document-link/@format` (to reference this attribute to the `FileFormat` codelist) - Done in IATI/IATI-Codelists#123
- [x] Update Codelist mapping file for `iati-activities/iati-activity/result/indicator/period/target/document-link/title/narrative/@xml:lang` (to reference this attribute to the `Language` codelist) - Not needed, as [paths for all `xml:lang` attributes already exist](https://github.com/IATI/IATI-Codelists/blob/694518226f67a5de88df251e27477d49cf29b4de/mapping.xml#L296-L299)
- [x] Update Codelist mapping file for `iati-activities/iati-activity/result/indicator/period/target/document-link/description/narrative/@xml:lang` (to reference this attribute to the `Language` codelist) - Not needed, as [paths for all `xml:lang` attributes already exist](https://github.com/IATI/IATI-Codelists/blob/694518226f67a5de88df251e27477d49cf29b4de/mapping.xml#L296-L299)
- [x] Update Codelist mapping file for `iati-activities/iati-activity/result/indicator/period/target/document-link/category/@code` (to reference this attribute to the `DocumentCategory` codelist) - Done in IATI/IATI-Codelists#123
- [x] Update Codelist mapping file for `iati-activities/iati-activity/result/indicator/period/target/document-link/language/@code` (to reference this attribute to the `Language` codelist) - Done in IATI/IATI-Codelists#123

- [x] Update Codelist mapping file for `iati-activities/iati-activity/result/indicator/period/actual/document-link/@format` (to reference this attribute to the `FileFormat` codelist) - Done in IATI/IATI-Codelists#123
- [x] Update Codelist mapping file for `iati-activities/iati-activity/result/indicator/period/actual/document-link/title/narrative/@xml:lang` (to reference this attribute to the `Language` codelist) - Not needed, as [paths for all `xml:lang` attributes already exist](https://github.com/IATI/IATI-Codelists/blob/694518226f67a5de88df251e27477d49cf29b4de/mapping.xml#L296-L299)
- [x] Update Codelist mapping file for `iati-activities/iati-activity/result/indicator/period/actual/document-link/description/narrative/@xml:lang` (to reference this attribute to the `Language` codelist) - Not needed, as [paths for all `xml:lang` attributes already exist](https://github.com/IATI/IATI-Codelists/blob/694518226f67a5de88df251e27477d49cf29b4de/mapping.xml#L296-L299)
- [x] Update Codelist mapping file for `iati-activities/iati-activity/result/indicator/period/actual/document-link/category/@code` (to reference this attribute to the `DocumentCategory` codelist) - Done in IATI/IATI-Codelists#123
- [x] Update Codelist mapping file for `iati-activities/iati-activity/result/indicator/period/actual/document-link/language/@code` (to reference this attribute to the `Language` codelist) - Done in IATI/IATI-Codelists#123

- [x] Merge https://github.com/IATI/IATI-Codelists/pull/123 to the correct branch - Done in IATI/IATI-Codelists#132

**Comment by dalepotter** [comment]
~Suggest this awaits merging of #372 to reduce merge dependencies.~ Now resolved!

**Comment by dalepotter** [comment]
According to the [final proposal spreadsheet](https://docs.google.com/spreadsheets/d/1XWnzesMvLebIVLk47OIXATfhcjESVcaGnw8SJpOuCCk/edit#gid=595223309), both the new `iati-activities/iati-activity/result/document-link` and `iati-activities/iati-activity/result/indicator/document-link` elements appear in between the `title` and `description` elements for their respective parents.

This may be intentional (although this would be inconsistent with the order of elements at the `iati-activity` level, where  the order is `title`, `description`, [other elements], `document-link`)?

Perhaps @amy-silcock or @PetyaKangalova could clarify this?

**Comment by dalepotter** [comment]
After conversation with @PetyaKangalova last week, it was confirmed that the new elements `iati-activities/iati-activity/result/document-link` and `iati-activities/iati-activity/result/indicator/document-link` should be added below the existing `description` element.

**Comment by andylolz** [comment]
I don’t see a link back to the relevant proposal here. So for posterity, it’s here: https://discuss.iatistandard.org/t/add-document-link-to-results-indicator-included-2-03/895
