### ISSUE TITLE
Add new reference element (as a child of the result element)

### ISSUE THREAD

**Issue by dalepotter** [IATI/IATI-Schemas#362]
Add a new element iati-activities/iati-activity/result/reference with definition:

> A reference element to allow for the coded identification of a results framework.

The element will have an occurrence rule of `0..*`.

This will also add the following sub-attributes/elements with definitions:

- `iati-activities/iati-activity/result/reference/@code` - occurs `1..1`, type xsd:string
> A code from the codelist identified in vocabulary that identifies a results framework

- `iati-activities/iati-activity/result/reference/@vocabulary` - occurs `1..1`
> A code for the results framework vocabulary. The code must be a valid value in the ResultVocabulary codelist

- `iati-activities/iati-activity/result/reference/@vocabulary-uri` - occurs `0..1`, type xsd:anyURI
> The URI where this vocabulary is defined. If the vocabulary is 99 or 98 (reporting organisation), the URI where this internal vocabulary is defined. While this is an optional field it is STRONGLY RECOMMENDED that all publishers use it to ensure that the meaning of their codes are fully understood by data users.

**Tasks:**

- [x] Add test cases - Done in IATI/IATI-Schemas#383
- [x] Add `iati-activities/iati-activity/result/reference` - Done in IATI/IATI-Schemas#383
- [x] Add `iati-activities/iati-activity/result/reference/@code` - Done in IATI/IATI-Schemas#383
- [x] Add `iati-activities/iati-activity/result/reference/@vocabulary` - Done in IATI/IATI-Schemas#383
- [x] Update Codelist mapping file for `iati-activities/iati-activity/result/reference/@vocabulary` (to reference this attribute to the `ResultVocabulary` codelist)
- [x] Add `iati-activities/iati-activity/result/reference/@vocabulary-uri` - Done in IATI/IATI-Schemas#383

The addition of the new `ResultVocabulary` codelist has been [added as a new issue on the IATI-Codelists-NonEmbedded repository](https://github.com/IATI/IATI-Codelists-NonEmbedded/issues/181).
