### ISSUE TITLE
Add new dimension element (as a child of the baseline element)

### ISSUE THREAD

**Issue by dalepotter** [IATI/IATI-Schemas#366]
Add a new element `iati-activities/iati-activity/result/indicator/baseline/dimension` with definition:

> A category used for disaggregating the result by gender, age, etc.

The element will have an occurrence rule of `0..*` and will replicate the existing `iati-activities/iati-activity/result/indicator/period/actual/dimension` element.

This will also add the following sub-attributes with definitions:

- `iati-activities/iati-activity/result/indicator/baseline/dimension/@name` - occurs `0..1`, type `xsd:string`
> Freetext description of a category being disaggregated.

- `iati-activities/iati-activity/result/indicator/baseline/dimension/@value` - occurs `0..1`, type `xsd:string`
> Description of the value being disaggregated.

**Tasks:**

- [x] Add tests
- [x] Add `iati-activities/iati-activity/result/indicator/baseline/dimension`
- [x] Add `iati-activities/iati-activity/result/indicator/baseline/dimension/@name`
- [x] Add `iati-activities/iati-activity/result/indicator/baseline/dimension/@value`

**Comment by allthatilk** [comment]
This seems to have been completed so closing.
